package com.hospitalinfo.hospitalinformationsystem.ai;

import com.hospitalinfo.hospitalinformationsystem.entity.Medicine;
import com.hospitalinfo.hospitalinformationsystem.mapper.MedicineMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * 评测数据集初始化器
 * 从数据库中生成评测数据集（半自动标注）
 * 
 * 注意：此类不会在应用启动时自动运行
 * 如需自动运行评测，请使用 MedicineSearchBenchmarkRunner
 */
@Slf4j
@Component
@ConditionalOnProperty(name = "evaluation.auto-start", havingValue = "true", matchIfMissing = false)
@RequiredArgsConstructor
public class EvaluationDatasetInitializer {

    private final MedicineMapper medicineMapper;
    private final MedicineSearchEvaluator evaluator;

    /**
     * 初始化评测数据集（手动调用）
     */
    public void initialize() {
        log.info("========== 初始化评测数据集 ==========");
        
        // 方式1: 从数据库自动生成评测查询
        generateFromDatabase();
        
        // 方式2: 添加预定义标注数据（需要人工审核）
        addManualAnnotations();
        
        log.info("评测数据集初始化完成，共 {} 条评测用例", evaluator.getDatasetSize());
    }

    /**
     * 从数据库自动生成评测用例（基于药名匹配作为伪标签）
     * 警告：这是自动生成，实际使用时需要人工审核标注
     */
    private void generateFromDatabase() {
        // 获取所有药品
        List<Medicine> allMedicines = medicineMapper.selectList(null);
        
        if (allMedicines.isEmpty()) {
            log.warn("数据库中无药品数据，请先导入数据");
            return;
        }

        // 自动生成查询-药品映射（基于名称包含关系作为伪标签）
        // 注意：这是简化版，实际应该人工标注
        Map<String, Set<Long>> autoGenerated = new HashMap<>();
        
        for (Medicine med : allMedicines) {
            if (med.getName() == null) continue;
            
            // 以药品名作为查询，相关药品为自身（简化处理）
            String query = med.getName();
            Set<Long> relevantIds = new HashSet<>();
            relevantIds.add(med.getId());
            
            // 同一类药品可能相关（根据分类）
            if (med.getCategory() != null) {
                allMedicines.stream()
                    .filter(m -> med.getCategory().equals(m.getCategory()))
                    .filter(m -> !m.getId().equals(med.getId()))
                    .limit(3) // 最多加3个同类药品
                    .forEach(m -> relevantIds.add(m.getId()));
            }
            
            autoGenerated.put(query, relevantIds);
        }
        
        // 只取前50个用例，避免评测时间过长
        int count = 0;
        for (Map.Entry<String, Set<Long>> entry : autoGenerated.entrySet()) {
            if (count++ >= 50) break;
            evaluator.addGroundTruth(entry.getKey(), entry.getValue());
        }
        
        log.info("自动生成 {} 条评测用例（基于分类相似度）", Math.min(50, autoGenerated.size()));
    }

    /**
     * 添加人工审核的标注数据
     */
    private void addManualAnnotations() {
        // 症状 -> 相关药品ID（需要根据实际药品数据填充）
        // 以下为示例，需要根据你的实际药品数据调整
        
        Map<String, Set<Long>> manualAnnotations = new HashMap<>();
        
        // 示例1: 退烧止痛类
        // 需要先查询数据库获取实际ID后填充
        // manualAnnotations.put("发烧头痛", Set.of(1L, 5L, 10L));
        
        // 示例2: 感冒咳嗽类
        // manualAnnotations.put("咳嗽感冒", Set.of(2L, 8L, 15L));
        
        // 示例3: 胃肠道类
        // manualAnnotations.put("胃痛腹泻", Set.of(3L, 12L, 20L));
        
        // 示例4: 抗菌消炎类
        // manualAnnotations.put("消炎抗菌", Set.of(4L, 7L, 18L));
        
        // 示例5: 慢性病类
        // manualAnnotations.put("高血压", Set.of(6L, 11L, 25L));
        
        // 添加到评测器
        evaluator.addGroundTruthBatch(manualAnnotations);
        
        if (!manualAnnotations.isEmpty()) {
            log.info("添加 {} 条人工标注数据", manualAnnotations.size());
        }
    }

    /**
     * 打印评测数据集统计信息
     */
    public void printDatasetStats() {
        log.info("========== 评测数据集统计 ==========");
        log.info("总评测用例数: {}", evaluator.getDatasetSize());
        log.info("使用方法: evaluator.runFullEvaluation() 运行评测");
    }
}
